### ISSUE TITLE
Basinga running problem

### ISSUE THREAD

**Issue by strongsu** [charreau/Basinga#1]
Hi Julien Charreau,

Recently, I used your Basinga software, but it always displayed "Failed to execute (10Beprodrates)" when I calculated the 10Be production rates. I also tried Arcgis software 10.2, 10.6, and 10.8. Though I have followed your Technical description of Basinga and finished system requirements, they all failed. I have confused a long time. Would you give me any professional suggestions?

**Comment by SophieRothman** [comment]
Hello, thank you for producing such a useful toolbox! I'm having trouble using the production rates tool because when I try to open it, this error pops up (while the Denudation Rates tool opens without problem) . I am using ArcGIS Pro 2.8.0. Any ideas of what the problem is?
isLicensed Syntax Error:   File "D:\Users\srothman\Documents\basinga\Basinga_ArcGIS\Basinga.tbx#10Beprodrates.InitializeParameters.py", line 38
    self.params[4].enabled=1
                           ^
TabError: inconsistent use of tabs and spaces in indentation
